In [10]:
import pandas as pd
import numpy as np
import warnings
import pickle as pkl
warnings.filterwarnings("ignore")

In [11]:
data=pd.read_csv(r"../data/competition.csv")

In [12]:
data

    Lang                                               Text  label
0     en  rt iciciprulife yorker doosra bouncer surya ku...  icici
1     en  rt cognizantnews cognizant tie max life insura...    max
2     en  hibah takaful sun life insurance wasiat faraid...   tata
3     en  niva bupa niva bupa finally rejected claim sur...    max
4     en  hdfc life insurance posted net profit r crore ...   hdfc
..   ...                                                ...    ...
574   en  sbilife ashamed penalising year old man keepin...    sbi
575   en  singhumesh understand concern kindly note sbi ...    sbi
576   en  ammaradzim got similiar call person claimed pu...   tata
577   en  iciciprulife extremely dissatisfied service pr...  icici
578   en  rt singhumesh sbilife theofficialsbi thinking ...    sbi

[579 rows x 3 columns]

In [13]:
data["label"].value_counts()

label
tata     180
sbi      153
hdfc      82
icici     70
max       64
xl        30
Name: count, dtype: int64

In [14]:
data_tata=data[data["label"]=="tata"]
data_sbi=data[data["label"]=="sbi"]
data_hdfc=data[data["label"]=="hdfc"]
data_icici=data[data["label"]=="icici"]
data_max=data[data["label"]=="max"]
data_xl=data[data["label"]=="xl"]

In [21]:
def intent(s):
    s=[s]
    intent_model=pkl.load(open('../models/intent_classification.pkl','rb'))
    intent_tfidf=pkl.load(open('../models/intent_classification_tfidf.pkl','rb'))
    d=intent_model.predict(intent_tfidf.transform(s))
    if d[0][0]==1:
        return "enquiry"
    elif d[0][1]==1:
        return "general talk"
    else:
        return "complaint"

In [22]:
def insurance(s):
    insurance_model=pkl.load(open('../models/insurance-classification_model.pkl','rb'))
    insurance_tfidf=pkl.load(open('../models/insurance_classification_tfidf.pkl','rb'))
    d=insurance_model.predict(insurance_tfidf.transform([s]))
    if d[0][0]==1:
        return "home"
    elif d[0][1]==1:
        return "life"
    elif d[0][2]==1:
        return "motor"
    elif d[0][3]==1:
        return "travel"
    else:
        return "health"

In [23]:
def service(s):
    service_model=pkl.load(open('../models/service_model.pkl','rb'))
    service_tfidf=pkl.load(open('../models/service_model_tfidf.pkl','rb'))
    d=service_model.predict(service_tfidf.transform([s]))
    if d[0][0]==1:
        return "emi"
    elif d[0][1]==1:
        return "insurance"
    elif d[0][2]==1:
        return "investment"
    elif d[0][3]==1:
        return "loan"
    elif d[0][4]==1:
        return "savings"
    else:
        return "card"

In [24]:
def sentiment(s):
    sentiment_model=pkl.load(open('../models/sentiment_clf.pkl','rb'))
    sentiment_tfidf=pkl.load(open('../models/sentiment_tfidf.pkl','rb'))
    d=sentiment_model.predict(sentiment_tfidf.transform([s]))
    if d[0]==1:
        return "positive"
    else:
        return "negative"

In [25]:
data_tata["sentiment"]=data_tata["Text"].apply(lambda x: sentiment(x))
data_tata["intent"]=data_tata["Text"].apply(lambda x: intent(x))
data_tata["service"]=data_tata["Text"].apply(lambda x: service(x))

In [26]:
data_tata

,Lang,Text,label,sentiment,intent,service
2,en,hibah takaful sun life insurance wasiat faraid...,tata,negative,complaint,card
7,en,lalit kumar thank sharing detail u get back wi...,tata,positive,complaint,insurance
9,en,live session zoom youtube tata aia leader prof...,tata,positive,general talk,card
10,en,pradeepk hi pradeep kalkhundiya kindly share d...,tata,positive,complaint,insurance
13,en,tataaia life dear people currently following l...,tata,positive,complaint,card
...,...,...,...,...,...,...
560,en,sanghavi jainam hi jainam sanghavi yet receive...,tata,positive,complaint,insurance
563,en,gontiprashanth hi prashanth gonti kindly share...,tata,positive,complaint,insurance
570,en,jackbankhandi dear jyoti please dm u mobile nu...,tata,positive,complaint,insurance
571,en,dhirens hi dhiren shah kindly share detail req...,tata,positive,complaint,insurance
576,en,ammaradzim got similiar call person claimed pu...,tata,positive,complaint,insurance